# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2021 Shanghai StarFive Technology Co., Ltd.
# TekkamanV <tekkamanv@starfivetech.com>

ifdef CONFIG_SPL_BUILD
obj-y	+= spl.o
endif
obj-y	+= jh7100.o
obj-y	+= jh_ptc.o
